server:
  port: 8080
spring:
  h2:
    console.path: /h2-console
    console.settings.trace: false
    spring.h2.console.settings.web-allow-others: false
  data:
    rest:
      basePath=/api:
  datasource:
    url: jdbc:h2:mem:survey
    username: root
    password: 123456
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
